### ISSUE TITLE
lost git info using `cabal v2-install`

### ISSUE THREAD

**Issue by jneira** [acfoltzer/gitrev#23]
* `cabal v2-install` builds the excutable in a temp directory, instead use the generated locally in the project dir
  * in that directory there is no .git to extract the required info
* `cabal v2-run my-program` works as intended
* the workaround is to use the local copy of the executable inside `dist-newstyle`, generated by `cabal v2-build`
* not sure if the solution could be being able to use a directory outside the project (see #18)

**Comment by jsoo1** [comment]
I just ran into the same issue

**Comment by s5k6** [comment]
Hi,

I would like to point out [this issue](https://github.com/haskell/cabal/issues/7488) I've just raised at Cabal.  I think instead of working around/against `cabal v2-install`, making Cabal discern files generated before sdist and after, would solve this issue, and maybe others.

In the issue referenced above, I'm asking for feedback and insights from people with a deeper understanding of the Cabal build process.  Maybe you could chime in over there…

Cheers
Stefan
